In [16]:
# Task 1

import requests as rs

r = rs.get("https://gsom.spbu.ru/en/")

if r.status_code == 200:
    print("The number of links to 'PNG' files on the site -" ,str(r.content).count('.png'))
elif r.status_code == 400:
    print("Error. Page not found")    
    
    

The number of links to 'PNG' files on the site - 28


In [71]:
# Finding the index of the right border
a1 = str(r.content).find('.png')

# Finding the index of the left borfer
a2 = str(r.content)[:a1].rfind('"')

# Creating a substring of the image link including the "png" and excluding the '"' at the left border
sub = str(r.content)[a2+1:a1+4]

# Full link
lnk = "https://gsom.spbu.ru" + sub
img = rs.get(lnk)
file = open('/home/jovyan/PyProjects/Unix_projects/logo.png', 'wb')
file.write(img.content)

28109

In [32]:
# Task 2

import numpy as np

# Income of 3 depertments each month over a 10-month period
no_tax = np.array([[20, 23, 34, 41, 35, 26, 47, 18, 29, 30],
              [12, 15, 38, 25, 37, 24, 36, 24, 17, 21],
              [64, 63, 82, 71, 83, 63, 79, 83, 77, 71]])
print("Incomes before tax\n", no_tax)

# 30% Tax
w_tax = no_tax - (no_tax * 0.3)
print("Income after tax\n", w_tax)

# Adjusted Tax
a = np.array([0.7, 0.7, 0.7, 0.7, 0.6, 0.6, 0.6, 0.7, 0.7, 0.7]) 
adj_tax = no_tax * a
print("Income with adjusted tax\n", adj_tax)

# Second Quarter
q_2 = adj_tax[:, 3:6]
print("Second quarter income\n", q_2)

Incomes before tax
 [[20 23 34 41 35 26 47 18 29 30]
 [12 15 38 25 37 24 36 24 17 21]
 [64 63 82 71 83 63 79 83 77 71]]
Income after tax
 [[14.  16.1 23.8 28.7 24.5 18.2 32.9 12.6 20.3 21. ]
 [ 8.4 10.5 26.6 17.5 25.9 16.8 25.2 16.8 11.9 14.7]
 [44.8 44.1 57.4 49.7 58.1 44.1 55.3 58.1 53.9 49.7]]
Income with adjusted tax
 [[14.  16.1 23.8 28.7 21.  15.6 28.2 12.6 20.3 21. ]
 [ 8.4 10.5 26.6 17.5 22.2 14.4 21.6 16.8 11.9 14.7]
 [44.8 44.1 57.4 49.7 49.8 37.8 47.4 58.1 53.9 49.7]]
Second quarter income
 [[28.7 21.  15.6]
 [17.5 22.2 14.4]
 [49.7 49.8 37.8]]
